package com.iot.entity;

import java.util.Date;
import lombok.Data;

@Data
public class LogInfoDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.id
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.create_time
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.update_time
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.level
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.msg
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    private String msg;
}