package com.iot.entity;

import java.util.Date;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

@Data
@TableName("log_info")
public class LogInfo extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.id
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    @TableId(value="id", type= IdType.AUTO)
    private Long id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.level
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.msg
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_info.logtime
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    private Date logtime;
}