package com.iot.mapper;

import com.iot.entity.LogInfoDo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface LogInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    int insert(LogInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    int insertSelective(LogInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    LogInfoDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    int updateByPrimaryKeySelective(LogInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 14:18:54 CST 2020
     */
    int updateByPrimaryKey(LogInfoDo record);
}