package com.iot.mapper;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.iot.entity.LogInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface LogInfoMapper extends BaseMapper<LogInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    int insertSelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    LogInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    int updateByPrimaryKeySelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_info
     *
     * @mbg.generated Tue Mar 17 16:57:04 CST 2020
     */
    int updateByPrimaryKey(LogInfo record);
}