server:
  port: 8080

spring:
  application:
    name: springboot-iot
  rabbitmq:
    host: 120.24.188.42
    port: 5672
    username: admin
    password: admin


  influx:
    #端口在/etc/influxdb/influxdb.conf的[http]中配置
    #此处需要[http://]否则会报错【Factory method 'influxDb' threw exception; nested exception is java.lang.IllegalArgumentException: Unable to parse url】
    url: http://120.24.188.42:8086
    user: admin
    password: admin
    database: test_iot
